name: auth_client
description: Auth Client
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  google_sign_in: ^5.4.1

  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
