name: parqueadero_app
description: parqueadero
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  auth_client: 
     path: packages/auth_client
  equatable: ^2.0.3

  firebase_core: ^1.22.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  go_router: ^4.5.0
  intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
